/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CorkBoardService } from "../corkBoard.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CorkBoardCreateInput } from "./CorkBoardCreateInput";
import { CorkBoardWhereInput } from "./CorkBoardWhereInput";
import { CorkBoardWhereUniqueInput } from "./CorkBoardWhereUniqueInput";
import { CorkBoardFindManyArgs } from "./CorkBoardFindManyArgs";
import { CorkBoardUpdateInput } from "./CorkBoardUpdateInput";
import { CorkBoard } from "./CorkBoard";
import { ThreadFindManyArgs } from "../../thread/base/ThreadFindManyArgs";
import { Thread } from "../../thread/base/Thread";
import { ThreadWhereUniqueInput } from "../../thread/base/ThreadWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CorkBoardControllerBase {
  constructor(
    protected readonly service: CorkBoardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CorkBoard })
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: CorkBoardCreateInput): Promise<CorkBoard> {
    return await this.service.create({
      data: {
        ...data,

        createdBy: data.createdBy
          ? {
              connect: data.createdBy,
            }
          : undefined,

        household: {
          connect: data.household,
        },
      },
      select: {
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        household: {
          select: {
            id: true,
          },
        },

        id: true,
        topic: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CorkBoard] })
  @ApiNestedQuery(CorkBoardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<CorkBoard[]> {
    const args = plainToClass(CorkBoardFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        household: {
          select: {
            id: true,
          },
        },

        id: true,
        topic: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CorkBoard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CorkBoardWhereUniqueInput
  ): Promise<CorkBoard | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        household: {
          select: {
            id: true,
          },
        },

        id: true,
        topic: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CorkBoard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CorkBoardWhereUniqueInput,
    @common.Body() data: CorkBoardUpdateInput
  ): Promise<CorkBoard | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          createdBy: data.createdBy
            ? {
                connect: data.createdBy,
              }
            : undefined,

          household: {
            connect: data.household,
          },
        },
        select: {
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          household: {
            select: {
              id: true,
            },
          },

          id: true,
          topic: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CorkBoard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CorkBoardWhereUniqueInput
  ): Promise<CorkBoard | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          household: {
            select: {
              id: true,
            },
          },

          id: true,
          topic: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/threads")
  @ApiNestedQuery(ThreadFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Thread",
    action: "read",
    possession: "any",
  })
  async findManyThreads(
    @common.Req() request: Request,
    @common.Param() params: CorkBoardWhereUniqueInput
  ): Promise<Thread[]> {
    const query = plainToClass(ThreadFindManyArgs, request.query);
    const results = await this.service.findThreads(params.id, {
      ...query,
      select: {
        corkboard: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        topic: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/threads")
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "update",
    possession: "any",
  })
  async connectThreads(
    @common.Param() params: CorkBoardWhereUniqueInput,
    @common.Body() body: ThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      threads: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/threads")
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "update",
    possession: "any",
  })
  async updateThreads(
    @common.Param() params: CorkBoardWhereUniqueInput,
    @common.Body() body: ThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      threads: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/threads")
  @nestAccessControl.UseRoles({
    resource: "CorkBoard",
    action: "update",
    possession: "any",
  })
  async disconnectThreads(
    @common.Param() params: CorkBoardWhereUniqueInput,
    @common.Body() body: ThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      threads: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
